### ISSUE TITLE
Unable to Install pyrasp Due to Metadata Generation Error with scikit-learn 1.3.0

### ISSUE THREAD

**Issue by RKeertishKumar** [rbidou/pyrasp#3]
Description:
When attempting to install the pyrasp package, I encountered an error related to metadata generation. The installation process fails while trying to prepare metadata for scikit-learn version 1.3.0, resulting in the inability to install pyrasp successfully. The error message suggests that there is a problem with compiling scikit-learn due to a missing cl.exe file.

Steps to Reproduce:

Attempt to install pyrasp using the command pip install pyrasp.
Observe the error during the metadata generation process for scikit-learn version 1.3.0.

```bash
pip install pyrasp
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pyrasp
  Downloading pyrasp-0.6.0-py3-none-any.whl.metadata (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 246.5 kB/s eta 0:00:00
Collecting sqlparse (from pyrasp)
  Downloading sqlparse-0.5.0-py3-none-any.whl.metadata (3.9 kB)
Collecting scikit-learn==1.3.0 (from pyrasp)
  Downloading scikit-learn-1.3.0.tar.gz (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 526.1 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 57, in spawn
          proc = subprocess.Popen(cmd, env=env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 419, in compile
          self.spawn(args)
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
          return super().spawn(cmd, env=env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 63, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed: {exc.args[-1]}") from exc
      distutils.errors.DistutilsExecError: command 'cl.exe' failed: None

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\aster\sem6\Research paper\Project\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\aster\sem6\Research paper\Project\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aster\sem6\Research paper\Project\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 626, in <module>
        File "<string>", line 620, in setup_package
        File "<string>", line 554, in configure_extension_modules
        File "C:\Users\aster\AppData\Local\Temp\pip-install-44htf0hg\scikit-learn_1318a249c2c846b09eed24036c8a350e\sklearn\_build_utils\__init__.py", line 46, in cythonize_extensions
          basic_check_build()
        File "C:\Users\aster\AppData\Local\Temp\pip-install-44htf0hg\scikit-learn_1318a249c2c846b09eed24036c8a350e\sklearn\_build_utils\pre_build_helpers.py", line 73, in basic_check_build
          compile_test_program(code)
        File "C:\Users\aster\AppData\Local\Temp\pip-install-44htf0hg\scikit-learn_1318a249c2c846b09eed24036c8a350e\sklearn\_build_utils\pre_build_helpers.py", line 31, in compile_test_program
          ccompiler.compile(
        File "C:\Users\aster\AppData\Local\Temp\pip-build-env-3mes28fc\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 421, in compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Expected Behavior:
The installation of pyrasp should proceed without errors, allowing users to use the package as intended.

Additional Information:
I found that upgrading scikit-learn to version 1.4.2 resolved the issue while installing scikit-learn. Was hoping changing the version would also allow pyrasp to work without issues. Therefore, it might be beneficial to consider upgrading the scikit-learn version in the dependencies of pyrasp to prevent similar issues for other users.

**Comment by rbidou** [comment]
It works on an empty environment. 

```
C:\Test>python -m venv venv

C:\Test>venv\Scripts\activate

(venv) C:\Test>pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 58.1.0

(venv) C:\Test>pip install pyrasp
Collecting pyrasp
  Using cached pyrasp-0.6.0-py3-none-any.whl (732 kB)
Collecting psutil
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting sqlparse
  Downloading sqlparse-0.5.0-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 KB ? eta 0:00:00
Collecting scikit-learn==1.3.0
  Using cached scikit_learn-1.3.0-cp310-cp310-win_amd64.whl (9.2 MB)
Collecting numpy>=1.17.3
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting scipy>=1.5.0
  Using cached scipy-1.13.0-cp310-cp310-win_amd64.whl (46.2 MB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.4.0-py3-none-any.whl (17 kB)
Collecting joblib>=1.1.1
  Using cached joblib-1.4.0-py3-none-any.whl (301 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.7-py3-none-any.whl (66 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Installing collected packages: urllib3, threadpoolctl, sqlparse, psutil, numpy, joblib, idna, charset-normalizer, certifi, scipy, requests, scikit-learn, pyrasp
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 joblib-1.4.0 numpy-1.26.4 psutil-5.9.8 pyrasp-0.6.0 requests-2.31.0 scikit-learn-1.3.0 scipy-1.13.0 sqlparse-0.5.0 threadpoolctl-3.4.0 urllib3-2.2.1

(venv) C:\Test>pip list
Package            Version
------------------ --------
certifi            2024.2.2
charset-normalizer 3.3.2
idna               3.7
joblib             1.4.0
numpy              1.26.4
pip                22.0.4
psutil             5.9.8
pyrasp             0.6.0
requests           2.31.0
scikit-learn       1.3.0
scipy              1.13.0
setuptools         58.1.0
sqlparse           0.5.0
threadpoolctl      3.4.0
urllib3            2.2.1

(venv) C:\Test>systeminfo

OS Name:                   Microsoft Windows 11 Professionnel
OS Version:                10.0.22631 N/A Build 22631
```

Anyway, scikit-learn 1.4.2 will be installed in version 6.1 expected around April 21st, that will ship with updated ML engines.
